name: CI
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.4
        with:
          PROJECT_FILE_PATH: Serialization.SubclassJsonConverter.Core/Serialization.SubclassJsonConverter.Core.csproj
          VERSION_FILE_PATH: Serialization.SubclassJsonConverter.Core/Serialization.SubclassJsonConverter.Core.csproj
          VERSION_REGEX: (.*)</Version>
          PACKAGE_NAME: Serialization.SubclassJsonConverter
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true
      
